Like and comment
jstnceronio/gibb-marketplace pull request #51
Opened 2022-05-23 08:40 UTC by alineammann

Has some bugs but like & comment is working.

2022-05-23 09:11 UTC, jstnceronio requested changes
Would move comment & comment-form to pages/post/comment

2022-05-23 09:21 UTC, alineammann commented on marketplace/src/app/pages/dashboard/dashboard.component.ts
> +    //return this.posts.filter(t => !t.doneDate).length / this.todoListService.todos.length * 100;
No, forgot to take it out

2022-05-23 16:55 UTC, jstnceronio approved these changes
I would've still created subfolders under post/comment but that's something for the backlog ...

2022-05-24 07:00 UTC, merged

2022-05-31 09:10 UTC, Akjo03 commented
closed #33

2022-05-31 09:10 UTC, Akjo03 commented
closes #33