85 make tribes great again
jstnceronio/gibb-marketplace pull request #87
Opened 2022-06-07 08:56 UTC by RoadJDK

2022-06-07 08:57 UTC, RoadJDK commented
pls like + subscribe

2022-06-07 09:04 UTC, Akjo03 submitted a review, later dismissed
- Add ngFor and multiselect to both tribe selections.
- Implement switch statement for easier addition of tribes

2022-06-07 09:04 UTC, Akjo03 commented on marketplace/src/app/shared/post/post.component.ts
> +  checkTribe() {
Switch statements would be better :)

2022-06-07 09:04 UTC, Akjo03 commented on marketplace/src/app/pages/post/create/create.component.html
>                        <option selected>Alle tribes</option> <!-- TODO: MULTISELECT FUNCTIONALITY AND NGFOR* ALL OPTIONS-->
same for here

2022-06-07 09:08 UTC, RoadJDK commented on marketplace/src/app/pages/dashboard/dashboard.component.html
> +            <option value="1">General</option>
no I cba its good as it is :)

2022-06-07 09:08 UTC, RoadJDK commented on marketplace/src/app/pages/post/create/create.component.html
>                        <option selected>Alle tribes</option> <!-- TODO: MULTISELECT FUNCTIONALITY AND NGFOR* ALL OPTIONS-->
🥇 nö

2022-06-07 09:09 UTC, Akjo03 commented on marketplace/src/app/shared/post/post.component.ts
> +  checkTribe() {
no it would allow for easier addition of new tribes

2022-06-07 09:10 UTC, Akjo03 commented on marketplace/src/app/shared/post/post.component.ts
> +  checkTribe() {
and it would change to a switch statement anyway

2022-06-07 09:14 UTC, RoadJDK commented
https://www.urbandictionary.com/define.php?term=Yogurt%20Male

2022-06-07 09:19 UTC, Akjo03 requested changes
Fixed the thing with the switch statement.

2022-06-07 09:19 UTC, Akjo03 commented on marketplace/src/app/pages/post/create/create.component.html
>                        <option selected>Alle tribes</option> <!-- TODO: MULTISELECT FUNCTIONALITY AND NGFOR* ALL OPTIONS-->
...

2022-06-07 09:19 UTC, Akjo03 commented on marketplace/src/app/pages/dashboard/dashboard.component.html
> +            <option value="1">General</option>
...

2022-06-07 09:25 UTC, Akjo03 requested changes
:)

2022-06-07 09:26 UTC, Akjo03 requested changes
Add the f*cking ngFors

2022-06-07 09:26 UTC, Akjo03 commented on marketplace/src/app/pages/dashboard/dashboard.component.html
>              <option selected>Alle tribes</option> <!-- TODO: NGFOR* ALL OPTIONS-->
Add ngFor here :)

2022-06-07 09:26 UTC, Akjo03 commented on marketplace/src/app/pages/post/create/create.component.html
>                        <option selected>Alle tribes</option> <!-- TODO: MULTISELECT FUNCTIONALITY AND NGFOR* ALL OPTIONS-->
Add ngFor here too

2022-06-07 17:27 UTC, Akjo03 commented
will do this tomorrow evening, documents are more important

2022-06-08 16:17 UTC, Akjo03 commented
@jstnceronio could youreview this?

2022-06-08 16:19 UTC, Akjo03 approved these changes
äll good now in my opinion. @jstnceronio check the merge too

2022-06-09 09:44 UTC, jstnceronio approved these changes
SHillig
![image](https://user-images.githubusercontent.com/52802645/172818236-21d72f73-f83d-4915-8eb4-20fdb025572c.png)

2022-06-09 09:46 UTC, merged